version: "3.8"
services:

  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    # ports: 
    #   - 8080:8080
    #   - 8081:8080
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: mydb
    volumes:
      - mysql-db:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    volumes:
      - adminer-mysql:/var/lib/adminer/
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports: 
      - 8081:80
    environment: 
      - PMA_ARBITRARY=1
    volumes:
      - phpmyadmin-mysql:/var/lib/phpmyadmin/

volumes: 
  phpmyadmin-mysql:
  adminer-mysql:
  mysql-db:
